### ISSUE TITLE
Unhandled Exception with a TODO Comment

### ISSUE THREAD

**Issue by zicklag** [sh-dave/kex-vox-kha#1]
Hi, I'm using your library to handle voxel triangulation for a [demo](https://github.com/zicklag/qub3d-armory-test) that I'm making and I am having a frequent issue that seemingly randomly occurs as I run the voxel mesh generator. Do you have any idea how to fix this?

https://github.com/sh-dave/kex-vox-kha/blob/37ae8b57353f71636397d6a27541b348e29b0efb/kex/vox/VoxelTools.hx#L97

**Comment by sh-dave** [comment]
Is it easy reproducible in this demo?

**Comment by zicklag** [comment]
I think I'm just starting to find a situation that breaks it. I'm going to update the demo and send an example when I figure it out.

**Comment by zicklag** [comment]
I updated the demo and here is a screenshot. I get a stack trace when I try to place a block on the underside of the arch.

![screenshot from 2018-08-18 16-22-48](https://user-images.githubusercontent.com/25393315/44303306-270a0e80-a303-11e8-9570-f7e564e08a08.png)

**Comment by zicklag** [comment]
FYI I'm not planning on doing much more, if anything, with my demo anyway, so it is not completely critical to me for this to be fixed. :slightly_smiling_face: The library worked great for my little demo. It was fun!

**Comment by sh-dave** [comment]
Ok, can reproduce it with the blend file, i'll try to fix anyway when i find the time.

**Comment by sh-dave** [comment]
I think something is wrong in your code, you push already existing voxels into the array. That in turn makes the algorithm explode. If i update `GameMain.placeBlockUnderMouse` to the following, i get the traces in the console and it won't explode any longer due to the return.

```haxe
if (!voxelOutOfBounds(newVoxel)) {
    for (v in this.voxels) {
 	if (v.x == newVoxel.x && v.y == newVoxel.y && v.z == newVoxel.z) {
            trace('voxel already exists');
            return;
        }
    }

    this.voxels.push(newVoxel);
...
```

**Comment by zicklag** [comment]
Aahhhhh, that explains it. Thanks. Sorry for bugging you about it then. I'll fix that. Thanks.
